### ISSUE TITLE
No imprime código de barras AFIP

### ISSUE THREAD

**Issue by adrianpaesani** [ingadhoc/aeroo_reports#6]
Al momento de imprimir el reporte no muestra el código de barras cuando está configurado como PDF, en formato ODT aparece perfectamente el código de barras.

**Comment by jjscarafia** [comment]
Mmm, la verdad me parece raro, este reporte debería agregar código de barras e imprimirlo bien en pdf, lo usan todos nuestros clientes: https://github.com/ingadhoc/argentina-reporting/blob/9.0/l10n_ar_aeroo_einvoice/einvoice.odt

Saludos!
